# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
