# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='pwd',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='VPN\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='VPN\u8d26\u53f7'),
        ),
    ]
