# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnicomRechargeGenOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(blank=True, default='', error_messages={'required': '\u7a0b\u5e8f\u540d\u4e0d\u80fd\u4e3a\u7a7a'}, max_length=255, null=True, unique=True, verbose_name='\u7a0b\u5e8f\u7f16\u53f7')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u4e0b\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
