# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicomrechargegenorder',
            name='eid',
            field=models.CharField(blank=True, default='', error_messages={'required': '\u7a0b\u5e8f\u540d\u4e0d\u80fd\u4e3a\u7a7a'}, max_length=255, null=True, verbose_name='\u7a0b\u5e8f\u7f16\u53f7'),
        ),
    ]
