# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u7a0b\u5e8f\u7f16\u53f7')),
                ('status', models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='\u72b6\u6001')),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u7a0b\u5e8f\u7c7b\u578b')),
                ('vpn_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='VPN\u7f16\u53f7')),
                ('ip_addr', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='IP\u5730\u5740')),
                ('os_type', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
