# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='os_type',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u7a0b\u5e8f\u7c7b\u578b'),
        ),
    ]
