# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_manage', '0002_auto_20170816_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='nodename',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u8282\u70b9\u540d'),
        ),
    ]
