# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_manage', '0003_program_nodename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True, verbose_name='\u7a0b\u5e8f\u7f16\u53f7'),
        ),
    ]
